### ISSUE TITLE
Gemini Tutor Chatbot

### ISSUE THREAD

**Issue by XavierTho** [XavierTho/cantella_backend#16]

**Comment by NolanYu1111** [comment]
[] Preparation: Research the Google Gemini API, OAuth 2.0, and integration steps. Set up the project in Google Cloud Console, enable the API, generate credentials, and plan the architecture for backend/frontend interaction and state management.

[] Backend Setup: Use a backend framework (e.g., Node.js, Python) to implement authentication (OAuth 2.0 or API key) and integrate the Gemini API by creating routes to handle chat requests. Set up a secure database for chat history or user data, validate API responses, and test error handling.

[] Frontend Setup: Build a responsive chat interface with input and message display, connecting it to the backend using fetch or Axios. Implement real-time updates with WebSockets or polling, manage state (chat history, loading states), and add CSS styling and animations for a polished experience.

[] Deployment: Deploy the backend on cloud platforms like Google Cloud or AWS and host the frontend on Vercel, Netlify, or Firebase. Integrate the chatbox with your website or app.

[] Post-Deployment: Monitor API usage, errors, and user behavior. Roll out updates based on feedback, optimize for scalability, and explore advanced features like voice input or multi-language support.
